- name: Rodar testes que passam
        uses: cypress-io/github-action@v6
        with:
          browser: electron        # ← era chrome
          spec: cypress/e2e/*.cy.js
        env:
          VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}

      - name: Rodar testes de bugs documentados
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          browser: electron        # ← era chrome
          spec: cypress/e2e/*.bugs.cy.js
        env:
          VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
```

